# Generated by Django 5.0.11 on 2025-02-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generic", "0002_alter_yqpointrecord_source_type_permissionblacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="openid",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="微信openid"
            ),
        ),
    ]
