# Generated by Django 5.0.14 on 2025-08-28 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_position_unique_position_per_person_org_semester_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="课程名称"
                    ),
                ),
                (
                    "course_type",
                    models.SmallIntegerField(
                        choices=[(0, "德"), (1, "智"), (2, "体"), (3, "美"), (4, "劳")],
                        verbose_name="课程类型",
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True, related_name="review_courses", to="app.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "4.测评课程列表",
                "verbose_name_plural": "4.测评课程列表",
                "ordering": ["course_name"],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="测评标题")),
                ("text", models.TextField(default="", verbose_name="详细评价")),
                (
                    "anonymous_flag",
                    models.BooleanField(default=False, verbose_name="是否匿名"),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "liked_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论者",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.reviewcategories",
                        verbose_name="测评课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "4. 课程测评",
                "verbose_name_plural": "4. 课程测评",
                "ordering": ["-time"],
            },
        ),
    ]
