# Generated by Django 5.0.14 on 2025-08-28 15:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_reviewcategories_coursereview"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="rating_content",
            field=models.SmallIntegerField(
                choices=[(1, "1分"), (2, "2分"), (3, "3分"), (4, "4分"), (5, "5分")],
                default=5,
                verbose_name="内容质量",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="rating_grade",
            field=models.SmallIntegerField(
                choices=[(1, "1分"), (2, "2分"), (3, "3分"), (4, "4分"), (5, "5分")],
                default=5,
                verbose_name="考核",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="rating_recommend",
            field=models.SmallIntegerField(
                choices=[(1, "1分"), (2, "2分"), (3, "3分"), (4, "4分"), (5, "5分")],
                default=5,
                verbose_name="总体评价",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="rating_workload",
            field=models.SmallIntegerField(
                choices=[(1, "1分"), (2, "2分"), (3, "3分"), (4, "4分"), (5, "5分")],
                default=5,
                verbose_name="工作量",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="school_year",
            field=models.SmallIntegerField(
                default=app.models.current_year, verbose_name="学年"
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="semester",
            field=models.CharField(
                choices=[("Fall", "秋"), ("Spring", "春"), ("Fall+Spring", "春秋")],
                default=app.models.current_semester,
                max_length=15,
                verbose_name="学期",
            ),
        ),
        migrations.AlterField(
            model_name="reviewcategories",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
