# Generated by Django 5.0.14 on 2025-08-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_coursereview_rating_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="teacher",
            field=models.CharField(
                blank=True, default="", max_length=48, verbose_name="授课教师"
            ),
        ),
    ]
