# Generated by Django 5.0.14 on 2025-08-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_coursereview_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="dislikes",
            field=models.IntegerField(default=0, verbose_name="点踩数"),
        ),
    ]
