# Generated by Django 5.0.14 on 2025-08-29 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_coursereview_dislikes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursereview",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="coursereview",
            name="liked_users",
        ),
        migrations.RemoveField(
            model_name="coursereview",
            name="likes",
        ),
        migrations.AddField(
            model_name="coursereview",
            name="visibility",
            field=models.BooleanField(default=True, verbose_name="是否可见"),
        ),
        migrations.AlterField(
            model_name="coursereview",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="ReviewReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    models.SmallIntegerField(
                        choices=[(0, "点赞"), (1, "点踩")], verbose_name="类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.coursereview",
                        verbose_name="测评",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "review")},
            },
        ),
    ]
